### ISSUE TITLE
Make sure to tag the assignments with given format eg Assignment1

### ISSUE THREAD

**Issue by patilav** [mukulbichkar19/WebDevSpring2016#1]

**Comment by mukulbichkar19** [comment]
Hi,
Ok so do you mean that the a in assignment1 should have been capital i.e. Assignment1  or is there any issue with the tag in general.

Thanks,
Mukul.

**Comment by patilav** [comment]
Kindly refer instructions on Course page and Piazza. :)

**Comment by mukulbichkar19** [comment]
Ok Thanks
